edible-items:
  APPLE:
    - FRUECHTE
    - ZUCKER
  GOLDEN_APPLE:
    - FRUECHTE
    - ZUCKER
  ENCHANTED_GOLDEN_APPLE:
    - FRUECHTE
  MELON_SLICE:
    - FRUECHTE
  CARROT:
    - FRUECHTE
  GOLDEN_CARROT:
    - FRUECHTE
  POTATO:
    - FRUECHTE
  BAKED_POTATO:
    - FRUECHTE
  BEETROOT:
    - FRUECHTE
  BREAD:
    - GETREIDE
  COOKED_BEEF:
    - FLEISCH
  COOKED_CHICKEN:
    - FLEISCH
  COOKED_MUTTON:
    - FLEISCH
  COOKED_PORKCHOP:
    - FLEISCH
  COOKED_RABBIT:
    - FLEISCH
  RABBIT_STEW:
    - FLEISCH
    - FRUECHTE
    - MILCH
  MUSHROOM_STEW:
    - FRUECHTE
  SUSPICIOUS_STEW:
    - FRUECHTE
  COD:
    - FLEISCH
  COOKED_COD:
    - FLEISCH
  SALMON:
    - FLEISCH
  COOKED_SALMON:
    - FLEISCH
  TROPICAL_FISH:
    - FLEISCH
  PUFFERFISH:
    - FLEISCH
  MILK_BUCKET:
    - MILCH
  CAKE:
    - MILCH
    - GETREIDE
    - ZUCKER
  COOKIE:
    - GETREIDE
    - ZUCKER
  SWEET_BERRIES:
    - FRUECHTE
  GLOW_BERRIES:
    - FRUECHTE
  HONEY_BOTTLE:
    - ZUCKER
  DRIED_KELP:
    - FRUECHTE
  PUMPKIN_PIE:
    - FRUECHTE
    - ZUCKER
    - GETREIDE
  BEETROOT_SOUP:
    - FRUECHTE
  CHORUS_FRUIT:
    - FRUECHTE