edible-items:
  APPLE:
    FRUECHTE: 2
    ZUCKER: 1
  GOLDEN_APPLE:
    FRUECHTE: 3
    ZUCKER: 1
  ENCHANTED_GOLDEN_APPLE:
    FRUECHTE: 4
    ZUCKER: 2
  MELON_SLICE:
    FRUECHTE: 1
  CARROT:
    FRUECHTE: 1
  GOLDEN_CARROT:
    FRUECHTE: 3
  POTATO:
    FRUECHTE: 1
  BAKED_POTATO:
    FRUECHTE: 2
  POISONOUS_POTATO:
    FRUECHTE: -3
  BEETROOT:
    FRUECHTE: 1
  BREAD:
    GETREIDE: 3
  COOKED_BEEF:
    FLEISCH: 4
  COOKED_CHICKEN:
    FLEISCH: 2
  COOKED_MUTTON:
    FLEISCH: 3
  COOKED_PORKCHOP:
    FLEISCH: 3
  COOKED_RABBIT:
    FLEISCH: 2
  RABBIT_STEW:
    FLEISCH: 3
    FRUECHTE: 2
    MILCH: 1
  MUSHROOM_STEW:
    FRUECHTE: 3
  SUSPICIOUS_STEW:
    FRUECHTE: 3
  COD:
    FLEISCH: 1
  COOKED_COD:
    FLEISCH: 2
  SALMON:
    FLEISCH: 1
  COOKED_SALMON:
    FLEISCH: 3
  TROPICAL_FISH:
    FLEISCH: 1
  PUFFERFISH:
    FLEISCH: 1
  MILK_BUCKET:
    MILCH: 4
  CAKE:
    MILCH: 1
    GETREIDE: 1
    ZUCKER: 2
  COOKIE:
    GETREIDE: 1
    ZUCKER: 1
  SWEET_BERRIES:
    FRUECHTE: 1
  GLOW_BERRIES:
    FRUECHTE: 1
  HONEY_BOTTLE:
    ZUCKER: 3
  DRIED_KELP:
    FRUECHTE: 1
  PUMPKIN_PIE:
    FRUECHTE: 2
    ZUCKER: 2
    GETREIDE: 1
  BEETROOT_SOUP:
    FRUECHTE: 3
  CHORUS_FRUIT:
    FRUECHTE: 2
  BEEF:
    FLEISCH: 1
  CHICKEN:
    FLEISCH: 1
  PORKCHOP:
    FLEISCH: 1
  MUTTON:
    FLEISCH: 1
  RABBIT:
    FLEISCH: 1
  ROTTEN_FLESH:
    FLEISCH: -1
  SPIDER_EYE:
    FLEISCH: -1
  EGG:
    FLEISCH: 1